modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "serverswitcher"
version = "${version}"
displayName = "ServerSwitcher"
authors = "furryAxw"
description = '''
本模组是FurryAxw Server Group的专用前置组件。 它的主要作用是与服务器的代理端（Velocity）进行通讯，自动识别你当前运行的整合包版本，并将你无缝引导至正确的子服务器。
'''

[[dependencies.serverswitcher]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.serverswitcher]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.serverswitcher]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"
